"""Update shop settings for route bank details

Revision ID: 04a7852f30b3
Revises: 836b98cf1fba
Create Date: 2026-08-14 00:10:03.717668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a7852f30b3'
down_revision: Union[str, None] = '836b98cf1fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('beneficiary_name', sa.String(length=255), nullable=True))
    op.add_column('shop_settings', sa.Column('encrypted_bank_account', sa.String(length=255), nullable=True))
    op.add_column('shop_settings', sa.Column('bank_account_last4', sa.String(length=4), nullable=True))
    op.add_column('shop_settings', sa.Column('ifsc_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'ifsc_code')
    op.drop_column('shop_settings', 'bank_account_last4')
    op.drop_column('shop_settings', 'encrypted_bank_account')
    op.drop_column('shop_settings', 'beneficiary_name')
    # ### end Alembic commands ###
