"""auto_update

Revision ID: 0f61042bdb50
Revises: 782760b1fe8e
Create Date: 2026-06-01 15:32:44.366009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f61042bdb50'
down_revision: Union[str, None] = '782760b1fe8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('allow_ice_preference', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('menu_items', sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('menu_items', sa.Column('addons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'addons')
    op.drop_column('menu_items', 'variants')
    op.drop_column('menu_items', 'allow_ice_preference')
    # ### end Alembic commands ###
