"""Add refund_id to Order

Revision ID: 2aa35bfc3c66
Revises: bdf8fb3cfb87
Create Date: 2026-08-19 11:06:41.674790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa35bfc3c66'
down_revision: Union[str, None] = 'bdf8fb3cfb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('refund_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'refund_id')
    # ### end Alembic commands ###
