"""Add discovery settings

Revision ID: 2e9d12cce89b
Revises: 8a00d639bb56
Create Date: 2026-06-05 12:47:46.307222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9d12cce89b'
down_revision: Union[str, None] = '8a00d639bb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('is_discoverable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('shop_settings', sa.Column('show_menus_in_discovery', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'show_menus_in_discovery')
    op.drop_column('shop_settings', 'is_discoverable')
    # ### end Alembic commands ###
