"""Add ice preference

Revision ID: 3f0453af6ecb
Revises: dc0853a644c0
Create Date: 2026-06-01 12:41:37.207259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0453af6ecb'
down_revision: Union[str, None] = 'dc0853a644c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('allow_ice_preference', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'allow_ice_preference')
    # ### end Alembic commands ###
