"""Add display_order to discount

Revision ID: 46307d7e43ce
Revises: e394c8be7465
Create Date: 2026-06-16 00:02:44.327485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add display_order to discount

Revision ID: 46307d7e43ce
Revises: e394c8be7465
Create Date: 2026-06-16 00:02:44.327485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46307d7e43ce'
down_revision: Union[str, None] = 'e394c8be7465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'display_order')
    # ### end Alembic commands ###
