"""Add display_order to Discount

Revision ID: 54c551a037e3
Revises: fa4445bf1363
Create Date: 2026-06-22 00:12:11.016990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c551a037e3'
down_revision: Union[str, None] = 'fa4445bf1363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'display_order')
    # ### end Alembic commands ###
