"""add google reviews fields

Revision ID: 785a1a5c334a
Revises: c1d2e3f4g5h6
Create Date: 2026-06-04 16:24:11.740580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785a1a5c334a'
down_revision: Union[str, None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('google_review_link', sa.String(length=500), nullable=True))
    op.add_column('shops', sa.Column('review_widget_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'review_widget_code')
    op.drop_column('shops', 'google_review_link')
    # ### end Alembic commands ###
