"""Add availability to discounts

Revision ID: 81c6b1f3b7d1
Revises: 0612d1c46553
Create Date: 2026-06-08 10:40:14.152430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c6b1f3b7d1'
down_revision: Union[str, None] = '0612d1c46553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('available_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('discounts', sa.Column('available_time_presets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'available_time_presets')
    op.drop_column('discounts', 'available_days')
    # ### end Alembic commands ###
