"""Add razorpay_account_id to shop_settings

Revision ID: 836b98cf1fba
Revises: fix_cust_ord_cols_101
Create Date: 2026-08-13 23:40:27.773902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836b98cf1fba'
down_revision: Union[str, None] = 'fix_cust_ord_cols_101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('razorpay_account_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'razorpay_account_id')
    # ### end Alembic commands ###
