"""add settlement fields to order

Revision ID: 917313482120
Revises: e7be5cece7ca
Create Date: 2026-08-14 03:10:54.752977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917313482120'
down_revision: Union[str, None] = 'e7be5cece7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('settlement_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('razorpay_settlement_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_settlement_id')
    op.drop_column('orders', 'settled_at')
    op.drop_column('orders', 'settlement_status')
    # ### end Alembic commands ###
