"""Add OAuth 2.1 models

Revision ID: 976b1034a671
Revises: 2aa35bfc3c66
Create Date: 2026-08-20 15:46:40.943331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976b1034a671'
down_revision: Union[str, None] = '2aa35bfc3c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_auth_codes',
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_auth_codes_client_id'), 'oauth_auth_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_auth_codes_code_hash'), 'oauth_auth_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_oauth_auth_codes_user_id'), 'oauth_auth_codes', ['user_id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('grant_types', sa.JSON(), nullable=False),
    sa.Column('response_types', sa.JSON(), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=50), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_table('oauth_refresh_tokens',
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from', sa.String(length=255), nullable=True),
    sa.Column('token_family_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_client_id'), 'oauth_refresh_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_token_family_id'), 'oauth_refresh_tokens', ['token_family_id'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_token_hash'), 'oauth_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_oauth_refresh_tokens_user_id'), 'oauth_refresh_tokens', ['user_id'], unique=False)
    op.alter_column('order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shop_settings', 'base_delivery_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('shop_settings', 'base_delivery_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('shop_settings', 'extra_delivery_distance_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('shop_settings', 'extra_delivery_charge_per_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_shops_area'), 'shops', ['area'], unique=False)
    op.create_index(op.f('ix_shops_category'), 'shops', ['category'], unique=False)
    op.create_index(op.f('ix_shops_city'), 'shops', ['city'], unique=False)
    op.create_index(op.f('ix_shops_cuisine'), 'shops', ['cuisine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_cuisine'), table_name='shops')
    op.drop_index(op.f('ix_shops_city'), table_name='shops')
    op.drop_index(op.f('ix_shops_category'), table_name='shops')
    op.drop_index(op.f('ix_shops_area'), table_name='shops')
    op.alter_column('shop_settings', 'extra_delivery_charge_per_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('shop_settings', 'extra_delivery_distance_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('shop_settings', 'base_delivery_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('shop_settings', 'base_delivery_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('order_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_oauth_refresh_tokens_user_id'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_token_hash'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_token_family_id'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_client_id'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_oauth_auth_codes_user_id'), table_name='oauth_auth_codes')
    op.drop_index(op.f('ix_oauth_auth_codes_code_hash'), table_name='oauth_auth_codes')
    op.drop_index(op.f('ix_oauth_auth_codes_client_id'), table_name='oauth_auth_codes')
    op.drop_table('oauth_auth_codes')
    # ### end Alembic commands ###
