"""add bogo combo

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-02 13:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6g7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('buy_quantity', sa.Integer(), nullable=True))
    op.add_column('discounts', sa.Column('get_quantity', sa.Integer(), nullable=True))
    op.add_column('discounts', sa.Column('reward_target_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('discounts', 'discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('discounts', 'reward_target_ids')
    op.drop_column('discounts', 'get_quantity')
    op.drop_column('discounts', 'buy_quantity')
    # ### end Alembic commands ###
