"""Add daily_order_number

Revision ID: bc4c5b81aa3d
Revises: f9c8d7e6b5a4
Create Date: 2026-09-21 20:42:27.264844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc4c5b81aa3d'
down_revision: Union[str, None] = 'f9c8d7e6b5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('daily_order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'daily_order_number')
    # ### end Alembic commands ###
