"""add razorpay_transfer_id to orders

Revision ID: bdf8fb3cfb87
Revises: 917313482120
Create Date: 2026-08-14 12:07:15.126894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf8fb3cfb87'
down_revision: Union[str, None] = '917313482120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_transfer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_transfer_id')
    # ### end Alembic commands ###
