"""add theme customization fields

Revision ID: be49f85bbc4f
Revises: 47676ed8c070
Create Date: 2026-06-22 02:49:26.741624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be49f85bbc4f'
down_revision: Union[str, None] = '47676ed8c070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_settings', sa.Column('theme_scope', sa.String(length=20), server_default='public', nullable=False))
    op.add_column('theme_settings', sa.Column('discount_card_style', sa.String(length=20), server_default='modern', nullable=False))
    op.add_column('theme_settings', sa.Column('menu_item_style', sa.String(length=20), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme_settings', 'menu_item_style')
    op.drop_column('theme_settings', 'discount_card_style')
    op.drop_column('theme_settings', 'theme_scope')
    # ### end Alembic commands ###
