"""add latitude longitude to shops

Revision ID: c1d2e3f4g5h6
Revises: 7f0a16449be0
Create Date: 2026-06-04 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = '7f0a16449be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'longitude')
    op.drop_column('shops', 'latitude')
    # ### end Alembic commands ###
