"""Add menu catalogs and branch overrides

Revision ID: cd14f47af018
Revises: 976b1034a671
Create Date: 2026-08-24 01:27:35.362068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd14f47af018'
down_revision: Union[str, None] = '976b1034a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_catalogs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_item_overrides',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('override_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_item_overrides_menu_item_id'), 'branch_item_overrides', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_branch_item_overrides_shop_id'), 'branch_item_overrides', ['shop_id'], unique=False)
    
    # 1. Add new columns
    op.add_column('shops', sa.Column('menu_catalog_id', sa.UUID(), nullable=True))
    op.add_column('categories', sa.Column('menu_catalog_id', sa.UUID(), nullable=True))
    op.add_column('discounts', sa.Column('menu_catalog_id', sa.UUID(), nullable=True))
    op.add_column('menu_items', sa.Column('menu_catalog_id', sa.UUID(), nullable=True))
    
    # 2. Migrate Data
    op.execute('''
        INSERT INTO menu_catalogs (id, user_id, name, created_at, updated_at)
        SELECT gen_random_uuid(), user_id, name || ' Menu', NOW(), NOW() FROM shops;
    ''')
    op.execute('''
        UPDATE shops SET menu_catalog_id = mc.id
        FROM menu_catalogs mc WHERE mc.name = shops.name || ' Menu' AND mc.user_id = shops.user_id;
    ''')
    op.execute('''
        UPDATE categories SET menu_catalog_id = s.menu_catalog_id
        FROM shops s WHERE categories.shop_id = s.id;
    ''')
    op.execute('''
        UPDATE menu_items SET menu_catalog_id = s.menu_catalog_id
        FROM shops s WHERE menu_items.shop_id = s.id;
    ''')
    op.execute('''
        UPDATE discounts SET menu_catalog_id = s.menu_catalog_id
        FROM shops s WHERE discounts.shop_id = s.id;
    ''')
    
    # 3. Make columns NOT NULL
    op.alter_column('categories', 'menu_catalog_id', nullable=False)
    op.alter_column('menu_items', 'menu_catalog_id', nullable=False)
    op.alter_column('discounts', 'menu_catalog_id', nullable=False)
    
    # 4. Clean up old shop_id and create FKs
    op.drop_index('ix_categories_shop_id', table_name='categories')
    op.create_index(op.f('ix_categories_menu_catalog_id'), 'categories', ['menu_catalog_id'], unique=False)
    op.drop_constraint('categories_shop_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'menu_catalogs', ['menu_catalog_id'], ['id'], ondelete='CASCADE')
    op.drop_column('categories', 'shop_id')
    
    op.drop_constraint('discounts_shop_id_fkey', 'discounts', type_='foreignkey')
    op.create_foreign_key(None, 'discounts', 'menu_catalogs', ['menu_catalog_id'], ['id'], ondelete='CASCADE')
    op.drop_column('discounts', 'shop_id')
    
    op.drop_index('ix_menu_items_shop_id', table_name='menu_items')
    op.create_index(op.f('ix_menu_items_menu_catalog_id'), 'menu_items', ['menu_catalog_id'], unique=False)
    op.drop_constraint('menu_items_shop_id_fkey', 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_catalogs', ['menu_catalog_id'], ['id'], ondelete='CASCADE')
    op.drop_column('menu_items', 'shop_id')
    
    op.create_index(op.f('ix_shops_menu_catalog_id'), 'shops', ['menu_catalog_id'], unique=False)
    op.create_foreign_key(None, 'shops', 'menu_catalogs', ['menu_catalog_id'], ['id'], ondelete='SET NULL')

    op.alter_column('qr_codes', 'user_id', existing_type=sa.UUID(), nullable=False)
    op.create_unique_constraint(None, 'qr_codes', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_index(op.f('ix_shops_menu_catalog_id'), table_name='shops')
    op.drop_column('shops', 'menu_catalog_id')
    op.drop_constraint(None, 'qr_codes', type_='unique')
    op.alter_column('qr_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('menu_items', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key('menu_items_shop_id_fkey', 'menu_items', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_menu_items_menu_catalog_id'), table_name='menu_items')
    op.create_index('ix_menu_items_shop_id', 'menu_items', ['shop_id'], unique=False)
    op.drop_column('menu_items', 'menu_catalog_id')
    op.add_column('discounts', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.create_foreign_key('discounts_shop_id_fkey', 'discounts', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('discounts', 'menu_catalog_id')
    op.add_column('categories', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_shop_id_fkey', 'categories', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_menu_catalog_id'), table_name='categories')
    op.create_index('ix_categories_shop_id', 'categories', ['shop_id'], unique=False)
    op.drop_column('categories', 'menu_catalog_id')
    op.drop_index(op.f('ix_branch_item_overrides_shop_id'), table_name='branch_item_overrides')
    op.drop_index(op.f('ix_branch_item_overrides_menu_item_id'), table_name='branch_item_overrides')
    op.drop_table('branch_item_overrides')
    op.drop_table('menu_catalogs')
    # ### end Alembic commands ###
