"""Add member exclusive discounts

Revision ID: d7673db7603d
Revises: 81c6b1f3b7d1
Create Date: 2026-06-14 19:53:58.318913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7673db7603d'
down_revision: Union[str, None] = '81c6b1f3b7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('visibility_type', sa.String(length=50), server_default='everyone_unlock_members', nullable=False))
    op.drop_column('discounts', 'members_only')
    op.add_column('otp_codes', sa.Column('contact_info', sa.String(length=255), server_default='', nullable=False))
    op.drop_index('ix_otp_codes_email', table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_contact_info'), 'otp_codes', ['contact_info'], unique=False)
    op.drop_column('otp_codes', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_codes_contact_info'), table_name='otp_codes')
    op.create_index('ix_otp_codes_email', 'otp_codes', ['email'], unique=False)
    op.drop_column('otp_codes', 'contact_info')
    op.add_column('discounts', sa.Column('members_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('discounts', 'visibility_type')
    # ### end Alembic commands ###
