"""Add is_retailer_added to memberships

Revision ID: e394c8be7465
Revises: d7673db7603d
Create Date: 2026-06-14 20:55:35.995078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e394c8be7465'
down_revision: Union[str, None] = 'd7673db7603d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_retailer_memberships', sa.Column('is_retailer_added', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_retailer_memberships', 'is_retailer_added')
    # ### end Alembic commands ###
