"""add razorpay route product and status

Revision ID: e7be5cece7ca
Revises: 04a7852f30b3
Create Date: 2026-08-14 01:37:08.738197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7be5cece7ca'
down_revision: Union[str, None] = '04a7852f30b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('razorpay_product_id', sa.String(length=100), nullable=True))
    op.add_column('shop_settings', sa.Column('razorpay_route_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'razorpay_route_status')
    op.drop_column('shop_settings', 'razorpay_product_id')
    # ### end Alembic commands ###
