"""Add opening and closing time to shops

Revision ID: eab5e7cc7f0a
Revises: 
Create Date: 2026-05-31 12:30:03.674283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab5e7cc7f0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('opening_time', sa.String(length=20), nullable=True))
    op.add_column('shops', sa.Column('closing_time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'closing_time')
    op.drop_column('shops', 'opening_time')
    # ### end Alembic commands ###
