"""add_indexes_on_shop_id_category_id

Revision ID: fa4445bf1363
Revises: e394c8be7465
Create Date: 2026-06-21 14:16:58.014593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4445bf1363'
down_revision: Union[str, None] = 'e394c8be7465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_shop_id'), 'categories', ['shop_id'], unique=False)
    op.drop_column('discounts', 'display_order')
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_shop_id'), 'menu_items', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_shop_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.add_column('discounts', sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_categories_shop_id'), table_name='categories')
    # ### end Alembic commands ###
